language: node_js
services:
- docker
cache:
  directories:
  - "~/.nvm"
  - node_modules
env:
  global:
  - RELEASE_BRANCH="master"
  - DOCKER_HUB_ACCOUNT="edenlablls"
  - MAIN_BRANCHES="master develop"
  - secure: "i7zBvWFddcUupE5aKfWyIINF/xG4TDxDO9n2Tdz2k4Lv2qs4mfopilXJKZwlHxRMDQaWcDsnxCnRzuxby9zABwzjtQf3ZQcqbYB/Nxg48OlD2vCE1ejG78Ef5/Y08/wWYQnzSwj0woJREuSRbn27HZ812fl7z0go2ftdml+jjv4GPmQUDCzFjnxKPyIONoYfzuLpAq+Hqg1ExmKjrVyxx4J8dYNHCNcGMLYxduNynQ+d83MLIoXTkxek78SlusfEzrlM8TpT0E3PSmjcui/0yAdYJZKlRo1uhH0UOcMrNjnGxUuOiBFFVp0qaYZTrGALrLA6MGIoP/2kxk96VQ1XbhXc+BRrXGuGYjo20oPqzGy3DcPhhPjvDoWFWRdQVftNts3VappOxlhM3cb2mFA3yvErLpeO1E+XNjWmEiiZkZHOUJwl4ZXo1lvQVxg32vZLsXuiDm8qUiTyooKIT2Q/IyE8e2be6/qqrfeLQNfkTzvhwzv1LjWcCTH4RfpqPbrTwwac6wt3H/PIOFA2qVpzC/5RYT2dwBDDwECKRDhHcH0wHjuLJFvlpDd7Yw7mUuotr/3DdFGUd/mAlO0QVc728XKrCraYLdQMaBo80d9/3EpbyugE05Q2Caur0z7LvC+0xwBea5MXQOgar7iXCLDRWrEUJlP+SugCRsBfNhLnHcA="
  - secure: "P/AxwEs+k13zpfR2w96rq2eeADBADHMErm1mvxBLfknX5+P8dbiMSiyL4l14XhpxF7Iye3AMfRUZ1HC1UgotEuK9Yq9C1lnshYoxXGW5D5HNAL7nsWibCCJ1ytzxoxDT/rwWPY/8ZCcypSi/0uQy/gzuSg02Uz6cpq843Z5fE/eUrysHmtqK96v/MCAgB81ypeQa1t+7z5TxwTFsF2eL7d+p5YQnPQStBTX/vQTANVePrfBGiwsIS46QOSWOiBT1fxEnAJQtERS6PStVlgPu1S4C0rN4czPBP5es7crHHaIgWde941pKoSkvsIIF/yYsUR5UvsSSxCTamo+OMnRG3xofZYNzznzIDI9N8UCzW7WzoAQ34HjVkZFLrhKkYstiCHT+br+hIOgmcAlm9KoygHEeTq2ldatCIdcAKqNDF9fbLMnlABhfysZT0/2kPCrwxgjqEMEChtqWcUK6k6APUcyKunkBGEs26bxZ3PK6T7ai9nFAjtygf0Z+I5i5LqObkPjQtvBmpXVMhJ/aNdrfgwUn3r4LbzZ7cVPbt6vHPeIjCPHKK7RVB9FQ1VCegUlsR11uBo+1b0vhhoyG+dapQ+jDVLukYIyVUOjXixkQW9cnjZ4pWtbuElNpKAIM79WlC0QdgjNtteLFfJ5cZzf80w9ONr9CSViHknj0vdMTYRQ="
node_js:
- 7.5.0
before_install:
- npm run docker:up
- chmod -R +x bin
script:
- npm run test
- npm run lint
- "./bin/version-increment.sh"
- "./bin/build.sh"
- "./bin/start.sh"
- sleep 5
- docker ps
- RUNNING_CONTAINERS=`docker ps | wc -l`; if [ "${RUNNING_CONTAINERS//[[:space:]]/}"
  == "1" ]; then echo "[E] Container is not started\!"; docker logs mithril.web --details
  --since 5h; exit 1; fi;
- npm run nightwatch -- -e travis
- sleep 5
after_failure:
- docker logs mithril.web
after_success:
- "./bin/ci/push.sh"
