language: node_js
services:
- docker
cache:
  directories:
  - "~/.nvm"
  - node_modules
env:
  global:
  - RELEASE_BRANCH="master"
  - DOCKER_HUB_ACCOUNT="edenlablls"
  - MAIN_BRANCHES="master develop"
  # Docker hub 
  - secure: "gqcY/XxBtmnNb67+CZVXOlh48/grzUSsOKjebO+Lsb/7z/72m6mcixbWL9HrIpzIOr/qI1lQVuWd1BsuNGiQvcu2numK3KfGZ7iFQrLw0S7kbZ8XANo4EooEiwwyU26Wp3mhvb9JMVONSDQZANbIJEo3unpCLiiB/QNinaG4wPZLTIYvtmIFZ+Vg3WBmrMqtjctUKEHEhsczC6VyQWVp3uTSf+3isNfO7I3/9JqZVPXokpnyDIEgfqDYy1Zfvihfx4kpuSzbUgU2zAfbYEPvrH7FLC6il0XafiKRt7x6EuJnM+E/fANCG03WjwOyODG7NpUN8n6lEAVS2zswZIsGMWzy+KLT40W/byiBbhtIFRebWFKrT697VeaHvJVP6nNCZdYwn6gt1WkXBj1KA8xtsPeuWl1DDxRR7ZUuoR1M/jGvQFZsLr805bgm8rRW2qzFl8Qp2cTncuh0tTyWJyFXjlhcqVGbuReKvuqUflNu9+Avga/OQvv+u2qeP/Ln7A5SItBfmp3dfwSGOwcGNgcW2SYUvPvEry9D3nrP1gXzwvMLa8CfkgqMRaQL2kbkUtk2vaJGfqro7vh/yVutPMU4gFko2JwWdyLCJDbFVemkIIaIDM5jhhYJEjYyCnzCMsv/rO6wLmascWPM0cr8pVBJZhiabRQe5Au97Z/fNP4M+vE="
  # Git 
  - secure: "p3o0V7y94dULgkN3a5Yht6cbzrD5QfBiYv5VaF607akpzUGHgh7Dl2RMLI1RMLgXm4nM5Xy5ZNWwNiGlMZn12AX2Pjscyc72gRwFhrRISjMvw7ma4ZD1Kc65faaGnQTmBDZvrHPPQr2TTfN72RfsRHT7crZg7Yubapil0RMDwjMAy7cPBqR8LrZXaZW/YwxDQLf/mqttJIUnEadB2Q39mwtzVmSLV3AJo9PpoqLS9TDxQtBNE26giq+KZzM3GksBVHQJWdcvRKpZSMR1sHdf1F0KHBOAXDG8aT1UOzuBg7YTwV7F1j6uXydF6eeXwzq/fjlU/x/4gkb1SmpRJ3HbvI9+kprtBpcULt+wcRWVfNsSUpBCVDHPC6WO4jvAn/D1RY9LVsBiUQI80OAf0/+16zORC+gGlZ2ep0jo+2KHc5UnvF7zZcH3H4rozMTonv2jbgvCR08OQPzD1T7YaDj6zKeoaAH93lcZ4anaYt1t5h3m+U0HZwjqBeQj0wExrSTW6uoVqREiztG5qsZm6D7sKrGfNgMnBwUaevGtQn+eBm6AScCGS+z+mAi8e4Y0ko6EtrWfSIXM55sYSL+vpZVLk5gIi1UcsEK2RMro2EVUCrfe5x1aHcQjkUMXRn+oogbT8mbORaqFvrlbXJNQZ48B/AM3uS3N7XvmW2+PycqXCm8="
node_js:
- 7.5.0
before_install:
- npm run docker:up
- chmod -R +x bin
script:
- npm run test
- npm run lint
- "./bin/version-increment.sh"
- "./bin/build.sh"
- "./bin/start.sh"
- sleep 5
- docker ps
- RUNNING_CONTAINERS=`docker ps | wc -l`; if [ "${RUNNING_CONTAINERS//[[:space:]]/}"
  == "1" ]; then echo "[E] Container is not started\!"; docker logs mithril.web --details
  --since 5h; exit 1; fi;
- npm run nightwatch -- -e travis
- sleep 5
after_failure:
- docker logs mithril.web
after_success:
- "./bin/ci/push.sh"
